In [2]:
import sys
import numpy as np
import pandas as pd

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
text=["London Paris Paris","Paris London London"]
cv=CountVectorizer()
count_matrix=cv.fit_transform(text) 

In [4]:
print(count_matrix.toarray())

[[1 2]
 [2 1]]


In [5]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_score = cosine_similarity(count_matrix)

In [6]:
print(similarity_score)

[[1.  0.8]
 [0.8 1. ]]


In [7]:
df=pd.read_csv("movie_dataset.csv")

In [9]:
df.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [27]:
df.shape

(4803, 25)

In [10]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [11]:
features=['keywords','cast','genres','director']

In [16]:
for feature in features:
    df[feature]=df[feature].fillna(' ')

In [17]:
def combine_feature(row):
    return row['keywords'] + row['cast'] + row['genres'] +row['director']

In [18]:
df['features']=df.apply(combine_feature,axis=1)

In [21]:
df['features']

0       culture clash future space war space colony so...
1       ocean drug abuse exotic island east india trad...
2       spy based on novel secret agent sequel mi6Dani...
3       dc comics crime fighter terrorist secret ident...
4       based on novel mars medallion space travel pri...
                              ...                        
4798    united states\u2013mexico barrier legs arms pa...
4799     Edward Burns Kerry Bish\u00e9 Marsha Dietlein...
4800    date love at first sight narration investigati...
4801     Daniel Henney Eliza Coupe Bill Paxton Alan Ru...
4802    obsession camcorder crush dream girlDrew Barry...
Name: features, Length: 4803, dtype: object

In [23]:
cv=CountVectorizer()
count_matrix=cv.fit_transform(df['features']) 
print(count_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
count_matrix.shape

(4803, 23544)

In [29]:
cosine_sim= cosine_similarity(count_matrix)

In [30]:
print(cosine_sim)

[[1.         0.03928371 0.04564355 ... 0.         0.         0.        ]
 [0.03928371 1.         0.         ... 0.0410305  0.         0.        ]
 [0.04564355 0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.0410305  0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [57]:
# to get title from the index
def get_title_from_index(index):
    return df[df.index==index]['title'].values[0]

In [58]:
# to get index from the title
def get_index_from_title(title):
    return df[df.title==title]['index'].values[0]

In [59]:
# movie that user like
movie_user_like="John Carter"

In [60]:
index=get_index_from_title(movie_user_like)

In [61]:
index

4

In [64]:
similar_movie=list(enumerate(cosine_sim[index]))
sorted_movie=sorted(similar_movie, key= lambda x:x[1], reverse=True)

In [72]:
i=0
for movie in sorted_movie:
    print(get_title_from_index(movie[0]))
    i=i+1;
    if i>50:
        break;

John Carter
Heaven is for Real
The Martian
American Psycho
Beastmaster 2: Through the Portal of Time
Auto Focus
The Adventurer: The Curse of the Midas Box
The Astronaut's Wife
Damnation Alley
The Other Side of Heaven
The Host
X-Men: Days of Future Past
Wing Commander
Treasure Planet
The Legend of Hell's Gate: An American Conspiracy
Maze Runner: The Scorch Trials
Dear John
Nerve
Spectre
The Jungle Book
The Number 23
Wild
Never Let Me Go
The Dead Zone
It's a Wonderful Life
Insurgent
Allegiant
A Scanner Darkly
Sin City
The Hunger Games: Catching Fire
Divergent
Jumper
Battlefield Earth
The Lucky One
Nancy Drew
Silent Running
Wild Wild West
Eragon
Contact
The Maze Runner
White Fang
Avatar
Street Fighter: The Legend of Chun-Li
Vampires
Alien
Cargo
Man of Steel
The Revenant
Superman II
The 5th Wave
Inherent Vice


In [69]:
get_title_from_index(index)

(4, 0.9999999999999996)